[Service]
MemoryMax=10G
CPUQuota=200%

# Restart the service when it exits with a non-zero code, is terminated by a signal, or times out.
Restart=on-failure

# Wait 15 seconds before attempting a restart (prevents instant, rapid failure loops)
RestartSec=15

# Limit attempts: If it fails 5 times within 30 seconds, stop trying.
StartLimitBurst=5
StartLimitIntervalSec=30
